export const projects = [
    {
        slug: "motorola-sales-analysis",
        title: "Motorola Sales Analysis",
        problem: "Track and analyze sales metrics using interactive dashboards to support decision-making.",
        dataset: "Sales data records",
        tools: ["Power BI", "DAX", "Data Modeling"],
        insights: [
            "Created interactive dashboards with DAX measures",
            "Optimized data models for performance",
            "Visualized key sales trends and metrics",
        ],
        category: "Power BI",
        image: "/dashboard-sales-analytics.jpg",
        fullDescription: "This project involved a comprehensive analysis of Motorola's sales data to identify key trends and performance metrics. By leveraging Power BI and DAX, interactive dashboards were created to provide stakeholders with actionable insights into sales performance across different regions and product lines.",
    },
    {
        slug: "sales-dashboard",
        title: "Sales Dashboard",
        problem: "Perform end-to-end sales analysis focusing on profit, customer segments, and regions.",
        dataset: "Retail sales dataset",
        tools: ["Tableau", "SQL", "Data Visualization"],
        insights: [
            "Analyzed profit margins across different regions",
            "Identified key customer segments",
            "Created comprehensive visual reports on Tableau Public",
        ],
        category: "Tableau",
        image: "/supply-chain-visualization.jpg",
        fullDescription: "An end-to-end sales analysis project that utilizes Tableau for visualization and SQL for data querying. The dashboard highlights critical KPIs such as profit margins, customer segmentation, and regional performance, enabling data-driven strategic decisions.",
    },
    {
        slug: "road-accident-analysis",
        title: "Road Accident Analysis",
        problem: "Analyze casualty data to identify patterns and improve road safety awareness.",
        dataset: "Road accident statistics",
        tools: ["Excel", "Pivot Tables", "Slicers"],
        insights: [
            "Built dashboard using PivotTables and Slicers",
            "Analyzed casualty trends by location and time",
            "Provided data-driven safety recommendations",
        ],
        category: "Excel",
        image: "/financial-dashboard.jpg",
        fullDescription: "This analysis focuses on road accident statistics to identify patterns related to casualties, locations, and time of day. Using Excel's advanced features like PivotTables and Slicers, the project delivers a user-friendly dashboard to monitor road safety trends.",
    },
    {
        slug: "customer-churn-analysis",
        title: "Customer Churn Analysis",
        problem: "Identify factors contributing to customer churn and develop retention strategies.",
        dataset: "Customer behavior data",
        tools: ["Python", "Pandas", "Matplotlib"],
        insights: [
            "Conducted EDA to find churn drivers",
            "Visualized customer retention patterns",
            "Proposed actionable strategies to reduce churn",
        ],
        category: "Python",
        image: "/customer-segmentation-chart.jpg",
        fullDescription: "A predictive analysis project aimed at understanding customer churn. By using Python libraries such as Pandas and Matplotlib, the project uncovers the underlying factors driving customer attrition and proposes strategies to improve retention rates.",
    },
]
